In [ ]:
import sys
from pathlib import Path

for candidate in (Path.cwd().resolve(), Path.cwd().resolve().parent):
    if (candidate / "loader.py").exists():
        if str(candidate) not in sys.path:
            sys.path.append(str(candidate))
        break

from loader import LoaderStorage

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# the list of airports we restirc ourselves to
airport_limit_list =["JFK","LAX","MIA","SFO","EWR","ORD","ATL","DFW","IAH",
"BOS","MCO","FLL","SEA","CLT","DEN","PHL","LAS","HNL","DTW","MSP","PHX","LGA","TPA",
"SLC","BWI","AUS","SAN","HOU","PDX","MDW","OAK","BNA","DCA","STL","DAL"]

SOURCE_ROOT = "/content/drive/MyDrive/Datamining/csv_files_sample"
DESTINATION_ROOT = "/content/drive/MyDrive/Datamining/Data_level1"
OTHER_DATA_ROOT = "/content/drive/MyDrive/Datamining/Other_Data_files"

source_storage = LoaderStorage(SOURCE_ROOT)
destination_storage = LoaderStorage(DESTINATION_ROOT)
other_data_storage = LoaderStorage(OTHER_DATA_ROOT)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
df = source_storage.read_csv(
    "On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2013_1.csv"
)
drop_cols =["DOT_ID_Reporting_Airline","IATA_CODE_Reporting_Airline","OriginAirportID","OriginAirportSeqID","OriginCityMarketID","OriginStateName",
            "OriginWac","DestAirportID","DestAirportSeqID","DestCityMarketID","DestStateName","DestWac","Flights",
            "DepDel15","DepartureDelayGroups","CancellationCode","Quarter","ArrDel15","ArrivalDelayGroups","ArrTimeBlk","DepTimeBlk",
            "DestCityName","DestState","DestStateFips","OriginState","OriginCityName","OriginStateFips"]
for idx,col in enumerate(df.columns):
    # print(idx, col)
    if idx > 60:
        drop_cols.append(col)

df = df.drop(columns=drop_cols)
display(df.head())
for idx,col in enumerate(df.columns):
    print(idx, col)
    # if idx > 60:
    #     drop_cols.append(col)

/tmp/ipykernel_12096/605343099.py:2: DtypeWarning: Columns (77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"/content/drive/MyDrive/Datamining/csv_files_sample/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2013_1.csv")

,Year,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,Origin,Dest,...,CRSElapsedTime,ActualElapsedTime,AirTime,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2013,1,17,4,2013-01-17,9E,N923XJ,3324,DFW,JFK,...,200.0,193.0,175.0,1391.0,6,NaN,NaN,NaN,NaN,NaN
1,2013,1,18,5,2013-01-18,9E,N907XJ,3324,DFW,JFK,...,200.0,202.0,178.0,1391.0,6,NaN,NaN,NaN,NaN,NaN
2,2013,1,19,6,2013-01-19,9E,N914XJ,3324,DFW,JFK,...,198.0,220.0,201.0,1391.0,6,0.0,0.0,17.0,0.0,0.0
3,2013,1,20,7,2013-01-20,9E,N921XJ,3324,DFW,JFK,...,200.0,198.0,176.0,1391.0,6,NaN,NaN,NaN,NaN,NaN
4,2013,1,21,1,2013-01-21,9E,N937XJ,3324,DFW,JFK,...,200.0,182.0,162.0,1391.0,6,NaN,NaN,NaN,NaN,NaN

0 Year
1 Month
2 DayofMonth
3 DayOfWeek
4 FlightDate
5 Reporting_Airline
6 Tail_Number
7 Flight_Number_Reporting_Airline
8 Origin
9 Dest
10 CRSDepTime
11 DepTime
12 DepDelay
13 DepDelayMinutes
14 TaxiOut
15 WheelsOff
16 WheelsOn
17 TaxiIn
18 CRSArrTime
19 ArrTime
20 ArrDelay
21 ArrDelayMinutes
22 Cancelled
23 Diverted
24 CRSElapsedTime
25 ActualElapsedTime
26 AirTime
27 Distance
28 DistanceGroup
29 CarrierDelay
30 WeatherDelay
31 NASDelay
32 SecurityDelay
33 LateAircraftDelay

In [ ]:
# limit to only soem origin and dest airports these are the 40 most trafficked airports in the US according to wikepedia
airport_limit_list =["JFK","LAX","MIA","SFO","EWR","ORD","ATL","DFW","IAH",
"BOS","MCO","FLL","SEA","CLT","DEN","PHL","LAS","HNL","DTW","MSP","PHX","LGA","TPA",
"SLC","BWI","AUS","SAN","HOU","PDX","MDW","OAK","BNA","DCA","STL","DAL"]

airline_limit_list = ["AS","AA","DL","F9","B6","WN","UA"]

# filter the dataframe to only include rows where the origin and dest airports are in the limit list
display(df.head())

,Year,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,Origin,Dest,...,CRSElapsedTime,ActualElapsedTime,AirTime,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2013,1,17,4,2013-01-17,9E,N923XJ,3324,DFW,JFK,...,200.0,193.0,175.0,1391.0,6,NaN,NaN,NaN,NaN,NaN
1,2013,1,18,5,2013-01-18,9E,N907XJ,3324,DFW,JFK,...,200.0,202.0,178.0,1391.0,6,NaN,NaN,NaN,NaN,NaN
2,2013,1,19,6,2013-01-19,9E,N914XJ,3324,DFW,JFK,...,198.0,220.0,201.0,1391.0,6,0.0,0.0,17.0,0.0,0.0
3,2013,1,20,7,2013-01-20,9E,N921XJ,3324,DFW,JFK,...,200.0,198.0,176.0,1391.0,6,NaN,NaN,NaN,NaN,NaN
4,2013,1,21,1,2013-01-21,9E,N937XJ,3324,DFW,JFK,...,200.0,182.0,162.0,1391.0,6,NaN,NaN,NaN,NaN,NaN

,Year,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,Origin,Dest,...,CRSElapsedTime,ActualElapsedTime,AirTime,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2013,1,17,4,2013-01-17,9E,N923XJ,3324,DFW,JFK,...,200.0,193.0,175.0,1391.0,6,NaN,NaN,NaN,NaN,NaN
1,2013,1,18,5,2013-01-18,9E,N907XJ,3324,DFW,JFK,...,200.0,202.0,178.0,1391.0,6,NaN,NaN,NaN,NaN,NaN
2,2013,1,19,6,2013-01-19,9E,N914XJ,3324,DFW,JFK,...,198.0,220.0,201.0,1391.0,6,0.0,0.0,17.0,0.0,0.0
3,2013,1,20,7,2013-01-20,9E,N921XJ,3324,DFW,JFK,...,200.0,198.0,176.0,1391.0,6,NaN,NaN,NaN,NaN,NaN
4,2013,1,21,1,2013-01-21,9E,N937XJ,3324,DFW,JFK,...,200.0,182.0,162.0,1391.0,6,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 1. Define only the columns you actually need
keep_cols = [col for col in df.columns if col not in drop_cols]

# convert the list to a dict with the data types for the columns we want to keep based on df
dtype_dict = {col: df[col].dtype for col in keep_cols}
display(dtype_dict)

# 2. Use a list to store dataframes temporarily
year_start = 14
year_end = 14
df_list = []
for j in range(year_start, year_end + 1):
    for i in range(1, 13):
        df_name = f"On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_20{j}_{i}.csv"
        try:
            # 3. Only read the necessary columns (Saves massive RAM)
            # 4. Force C engine to avoid Arrow mask issues
            df_part = source_storage.read_csv(
                df_name,
                usecols=keep_cols,
                dtype=dtype_dict,
                engine="c",
                low_memory=False
            )

            print(f"Processing Year: 20{j:02d}, Month: {i}")

            # 5. Filter immediately (Saves RAM for the final concat)
            mask = (
                df_part["Reporting_Airline"].isin(airline_limit_list) &
                (df_part["Origin"].isin(airport_limit_list) |
                df_part["Dest"].isin(airport_limit_list))
            )
            df_part = df_part[mask]

            df_list.append(df_part)

        except FileNotFoundError:
            print(f"Skipping: {df_name} not found.")

# 6. Concatenate everything once at the end
if df_list:
    df_all = pd.concat(df_list, ignore_index=True)
else:
    df_all = pd.DataFrame(columns=keep_cols)

# 7. Final cleanup
import gc
del df_list
gc.collect()

{'Year': dtype('int64'),
 'Month': dtype('int64'),
 'DayofMonth': dtype('int64'),
 'DayOfWeek': dtype('int64'),
 'FlightDate': dtype('O'),
 'Reporting_Airline': dtype('O'),
 'Tail_Number': dtype('O'),
 'Flight_Number_Reporting_Airline': dtype('int64'),
 'Origin': dtype('O'),
 'Dest': dtype('O'),
 'CRSDepTime': dtype('int64'),
 'DepTime': dtype('float64'),
 'DepDelay': dtype('float64'),
 'DepDelayMinutes': dtype('float64'),
 'TaxiOut': dtype('float64'),
 'WheelsOff': dtype('float64'),
 'WheelsOn': dtype('float64'),
 'TaxiIn': dtype('float64'),
 'CRSArrTime': dtype('int64'),
 'ArrTime': dtype('float64'),
 'ArrDelay': dtype('float64'),
 'ArrDelayMinutes': dtype('float64'),
 'Cancelled': dtype('float64'),
 'Diverted': dtype('float64'),
 'CRSElapsedTime': dtype('float64'),
 'ActualElapsedTime': dtype('float64'),
 'AirTime': dtype('float64'),
 'Distance': dtype('float64'),
 'DistanceGroup': dtype('int64'),
 'CarrierDelay': dtype('float64'),
 'WeatherDelay': dtype('float64'),
 'NASDelay': dtype('float64'),
 'SecurityDelay': dtype('float64'),
 'LateAircraftDelay': dtype('float64')}

Processing Year: 2014, Month: 1
Processing Year: 2014, Month: 2
Processing Year: 2014, Month: 3
Processing Year: 2014, Month: 4
Processing Year: 2014, Month: 5
Processing Year: 2014, Month: 6
Processing Year: 2014, Month: 7
Processing Year: 2014, Month: 8
Processing Year: 2014, Month: 9
Processing Year: 2014, Month: 10
Processing Year: 2014, Month: 11
Processing Year: 2014, Month: 12

0

In [ ]:
df_all = df_all[~((df_all['ArrTime'].isna()) & (df_all['Cancelled'] == 0) & (df_all['Diverted'] == 0))]

In [ ]:
# colums with times of day
time_cols =["CRSDepTime","DepTime","WheelsOff","WheelsOn","CRSArrTime","ArrTime"]

cancelled_mask = (df_all['Cancelled'] == 1)
diverted_mask = (df_all['Diverted'] == 1)
cancelled_or_diverted_mask = cancelled_mask | diverted_mask
for col in time_cols:
    missing_values = df_all[col].isna()
    df_all[col] = df_all[col].fillna(0).astype(int)
    # convert all 2400 values to 0000, because 2400 is not a valid time, but 0000 is
    df_all[col] = df_all[col].replace(2400, 0)
    df_all[col] = df_all[col].apply(lambda x: f"{x:04d}")
    df_all[col] = pd.to_datetime(df_all[col], format="%H%M", errors='coerce').dt.time
    # make all values NaT if the flight was canncelled
    df_all.loc[cancelled_mask & missing_values, col] = pd.NaT
df_all.loc[diverted_mask, 'WheelsOn'] = pd.NaT
df_all.loc[diverted_mask, 'ArrTime'] = pd.NaT

display(df_all[time_cols].head())

  CRSDepTime   DepTime WheelsOff  WheelsOn CRSArrTime   ArrTime
0   09:40:00  09:35:00  09:52:00  10:48:00   10:55:00  10:51:00
1   09:40:00  09:51:00  10:03:00  10:57:00   10:55:00  11:15:00
2   11:35:00  11:44:00  11:56:00  12:53:00   13:00:00  13:02:00
3   11:35:00  11:34:00  11:45:00  12:38:00   13:00:00  12:53:00
4   11:35:00  11:29:00  11:41:00  12:33:00   13:00:00  12:44:00

In [ ]:
num_rows = len(df_all)
dataset_completed_flights = df_all[(df_all['Cancelled'] == 0) & (df_all['Diverted'] == 0)]
for column in dataset_completed_flights.columns:
    if dataset_completed_flights[column].isna().sum() > 0:
        # calcuate the percentage of nan values in the column
        percentage_nan = dataset_completed_flights[column].isna().sum() / num_rows * 100
        print(f"Column {column} has {dataset_completed_flights[column].isna().sum()} nan values ({percentage_nan:.2f}%)")
# drop all rows where the arrival delay is Nan, even if the flight was not cancelled or diverted, because these are not useful for the model building

Column CarrierDelay has 2633191 nan values (77.05%)
Column WeatherDelay has 2633191 nan values (77.05%)
Column NASDelay has 2633191 nan values (77.05%)
Column SecurityDelay has 2633191 nan values (77.05%)
Column LateAircraftDelay has 2633191 nan values (77.05%)

In [ ]:
# load the airport dataset
airports = other_data_storage.read_csv("airports_with_runway_info.csv")
# only keep the iata_code and the Timezone
airports = airports[['iata_code','TZ']]
display(airports.head())

# get the unique values for TZ
print(airports['TZ'].unique())

  iata_code                TZ
0       ABE  America/New_York
1       ABQ    America/Denver
2       ACK  America/New_York
3       ALB  America/New_York
4       AMA   America/Chicago

['America/New_York' 'America/Denver' 'America/Chicago'
 'America/Los_Angeles' 'America/Phoenix' 'America/Anchorage'
 'America/Adak' 'Pacific/Honolulu' 'America/St_Thomas'
 'America/Puerto_Rico']

In [ ]:
# we want to calculate the turaround time of an aircraft
# to make this easier for now, we will reduce the dataset to only the relevant columns
dataset = df_all

# drop all flights, where the DEST or ORIGIN is "PFN"
dataset = dataset[(dataset['Origin'] != 'PFN') & (dataset['Dest'] != 'PFN')]
# we join the aiports dataset to get the timezone of the departure and arrival airports
dataset = dataset.merge(airports, left_on='Origin', right_on='iata_code', how='left')
dataset = dataset.merge(airports, left_on='Dest', right_on='iata_code', how='left', suffixes=('_Origin', '_Dest'))
dataset = dataset.drop(columns=['iata_code_Origin', 'iata_code_Dest'])

# step 1 is to get correct and reliable datetime objects in UTC and Local time for the departure and arrival times.
# we start with the departure time where we combine the filght date datetime with the daparture time timeobject to get a datetime object in local time
dataset['CRSDepDateTime'] = pd.to_datetime(dataset['FlightDate'] + ' ' + dataset['CRSDepTime'].astype(str), errors='coerce')
dataset['CRSDepDateTime_UTC'] = dataset.groupby('TZ_Origin')['CRSDepDateTime'].transform(
    lambda x: x.dt.tz_localize(x.name, ambiguous=True,nonexistent='shift_forward').dt.tz_convert('UTC')
)
# we convert the departure time to UTC time, by using the timezone of the departure airport

# we do the same for the arrival time
dataset['CRSArrDateTime'] = pd.to_datetime(dataset['FlightDate'] + ' ' + dataset['CRSArrTime'].astype(str), errors='coerce')
dataset['CRSArrDateTime_UTC'] = dataset.groupby('TZ_Dest')['CRSArrDateTime'].transform(
    lambda x: x.dt.tz_localize(x.name,ambiguous=True,nonexistent='shift_forward').dt.tz_convert('UTC')
)
# also convert the actual arrival and departure times to UTC time, by using the timezone of the departure and arrival airport
# check if the DepTime is smaller than the CRSDepTime, if it is, we add 1 day to the DepTime, because it means that the flight departed after midnight
mask = ((dataset['DepTime'] < dataset['CRSDepTime'] ) & (dataset['DepDelay'] > 0)).astype(int)

dataset['DepDateTime'] = pd.to_datetime(dataset['FlightDate'] + ' ' + dataset['DepTime'].astype(str), errors='coerce')
# add 1 day to the DepDateTime if the DepTime is smaller than the CRSDepTime, because it means that the flight departed after midnight
dataset['DepDateTime'] = dataset['DepDateTime'] + pd.to_timedelta(mask, unit='D')

dataset['DepDateTime_UTC'] = dataset.groupby('TZ_Origin')['DepDateTime'].transform(
    lambda x: x.dt.tz_localize(x.name, ambiguous=True,nonexistent='shift_forward').dt.tz_convert('UTC')
)
dataset['ArrDateTime'] = pd.to_datetime(dataset['FlightDate'] + ' ' + dataset['ArrTime'].astype(str), errors='coerce')
dataset['ArrDateTime_UTC'] = dataset.groupby('TZ_Dest')['ArrDateTime'].transform(
    lambda x: x.dt.tz_localize(x.name, ambiguous=True,nonexistent='shift_forward').dt.tz_convert('UTC')
)


# we check if the arrival time is before the departure time, if it is, we add 1 day to the arrival time
# we get a boolean mask where the arrival time is before the departure time
mask = (dataset['CRSArrDateTime_UTC'] < dataset['CRSDepDateTime_UTC']).astype(int)
dataset['CRSArrDateTime_UTC'] = dataset['CRSArrDateTime_UTC'] + pd.to_timedelta(mask, unit='D')
dataset['CRSArrDateTime'] = dataset['CRSArrDateTime'] + pd.to_timedelta(mask, unit='D')

mask = (dataset['ArrDateTime_UTC'] < dataset['DepDateTime_UTC']).astype(int)
dataset['ArrDateTime_UTC'] = dataset['ArrDateTime_UTC'] + pd.to_timedelta(mask, unit='D')
dataset['ArrDateTime'] = dataset['ArrDateTime'] + pd.to_timedelta(mask, unit='D')

display(dataset[['FlightDate','CRSDepTime', 'CRSDepDateTime', 'CRSDepDateTime_UTC', 'CRSArrTime', 'CRSArrDateTime_UTC']].head())

,FlightDate,CRSDepTime,CRSDepDateTime,CRSDepDateTime_UTC,CRSArrTime,CRSArrDateTime_UTC
0,2014-01-30,09:40:00,2014-01-30 09:40:00,2014-01-30 15:40:00+00:00,10:55:00,2014-01-30 16:55:00+00:00
1,2014-01-31,09:40:00,2014-01-31 09:40:00,2014-01-31 15:40:00+00:00,10:55:00,2014-01-31 16:55:00+00:00
2,2014-01-01,11:35:00,2014-01-01 11:35:00,2014-01-01 17:35:00+00:00,13:00:00,2014-01-01 19:00:00+00:00
3,2014-01-02,11:35:00,2014-01-02 11:35:00,2014-01-02 17:35:00+00:00,13:00:00,2014-01-02 19:00:00+00:00
4,2014-01-03,11:35:00,2014-01-03 11:35:00,2014-01-03 17:35:00+00:00,13:00:00,2014-01-03 19:00:00+00:00

In [ ]:
# make a temporary Collumn for k hours before departure
hours_before = 2
dataset["knownWeatherDateTime_UTC"] = dataset["CRSDepDateTime_UTC"] - pd.to_timedelta(hours_before, unit='h')
# round down to the previus full hour
dataset["knownWeatherDateTime_UTC"] = dataset["knownWeatherDateTime_UTC"].dt.floor('h')
# remove the timezone information, as the weather data does not have timezone information
dataset["knownWeatherDateTime_UTC"] = dataset["knownWeatherDateTime_UTC"].dt.tz_localize(None)

# merge with weather data on ORIGIN and knownWeatherDateTime_UTC

display(dataset)

,Year,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,Origin,Dest,...,TZ_Dest,CRSDepDateTime,CRSDepDateTime_UTC,CRSArrDateTime,CRSArrDateTime_UTC,DepDateTime,DepDateTime_UTC,ArrDateTime,ArrDateTime_UTC,knownWeatherDateTime_UTC
0,2014,1,30,4,2014-01-30,AA,N006AA,2377,DFW,ICT,...,America/Chicago,2014-01-30 09:40:00,2014-01-30 15:40:00+00:00,2014-01-30 10:55:00,2014-01-30 16:55:00+00:00,2014-01-30 09:35:00,2014-01-30 15:35:00+00:00,2014-01-30 10:51:00,2014-01-30 16:51:00+00:00,2014-01-30 13:00:00
1,2014,1,31,5,2014-01-31,AA,N003AA,2377,DFW,ICT,...,America/Chicago,2014-01-31 09:40:00,2014-01-31 15:40:00+00:00,2014-01-31 10:55:00,2014-01-31 16:55:00+00:00,2014-01-31 09:51:00,2014-01-31 15:51:00+00:00,2014-01-31 11:15:00,2014-01-31 17:15:00+00:00,2014-01-31 13:00:00
2,2014,1,1,3,2014-01-01,AA,N002AA,2377,ICT,DFW,...,America/Chicago,2014-01-01 11:35:00,2014-01-01 17:35:00+00:00,2014-01-01 13:00:00,2014-01-01 19:00:00+00:00,2014-01-01 11:44:00,2014-01-01 17:44:00+00:00,2014-01-01 13:02:00,2014-01-01 19:02:00+00:00,2014-01-01 15:00:00
3,2014,1,2,4,2014-01-02,AA,N002AA,2377,ICT,DFW,...,America/Chicago,2014-01-02 11:35:00,2014-01-02 17:35:00+00:00,2014-01-02 13:00:00,2014-01-02 19:00:00+00:00,2014-01-02 11:34:00,2014-01-02 17:34:00+00:00,2014-01-02 12:53:00,2014-01-02 18:53:00+00:00,2014-01-02 15:00:00
4,2014,1,3,5,2014-01-03,AA,N014AA,2377,ICT,DFW,...,America/Chicago,2014-01-03 11:35:00,2014-01-03 17:35:00+00:00,2014-01-03 13:00:00,2014-01-03 19:00:00+00:00,2014-01-03 11:29:00,2014-01-03 17:29:00+00:00,2014-01-03 12:44:00,2014-01-03 18:44:00+00:00,2014-01-03 15:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3417343,2014,12,31,3,2014-12-31,DL,N900DE,2655,JFK,RSW,...,America/New_York,2014-12-31 08:00:00,2014-12-31 13:00:00+00:00,2014-12-31 11:29:00,2014-12-31 16:29:00+00:00,2014-12-31 07:50:00,2014-12-31 12:50:00+00:00,2014-12-31 11:05:00,2014-12-31 16:05:00+00:00,2014-12-31 11:00:00
3417344,2014,12,31,3,2014-12-31,DL,N386DA,2656,SLC,LAX,...,America/Los_Angeles,2014-12-31 07:22:00,2014-12-31 14:22:00+00:00,2014-12-31 08:30:00,2014-12-31 16:30:00+00:00,2014-12-31 07:34:00,2014-12-31 14:34:00+00:00,2014-12-31 08:28:00,2014-12-31 16:28:00+00:00,2014-12-31 12:00:00
3417345,2014,12,31,3,2014-12-31,DL,N3762Y,2658,LAS,JFK,...,America/New_York,2014-12-31 11:59:00,2014-12-31 19:59:00+00:00,2014-12-31 19:49:00,2015-01-01 00:49:00+00:00,2014-12-31 11:51:00,2014-12-31 19:51:00+00:00,2014-12-31 19:15:00,2015-01-01 00:15:00+00:00,2014-12-31 17:00:00
3417346,2014,12,31,3,2014-12-31,DL,N954DL,2659,FLL,JFK,...,America/New_York,2014-12-31 19:20:00,2015-01-01 00:20:00+00:00,2014-12-31 22:12:00,2015-01-01 03:12:00+00:00,2014-12-31 19:14:00,2015-01-01 00:14:00+00:00,2014-12-31 21:57:00,2015-01-01 02:57:00+00:00,2014-12-31 22:00:00
3417347,2014,12,31,3,2014-12-31,DL,N995AT,2668,LGA,BOS,...,America/New_York,2014-12-31 06:59:00,2014-12-31 11:59:00+00:00,2014-12-31 08:11:00,2014-12-31 13:11:00+00:00,2014-12-31 07:01:00,2014-12-31 12:01:00+00:00,2014-12-31 08:05:00,2014-12-31 13:05:00+00:00,2014-12-31 09:00:00

In [ ]:
# save the cleaned data to a new csv file
destination_storage.write_parquet(dataset, "1_year_data.parquet", index=False)